#!/bin/bash

[ -f $HOME/.fehbg ] && . $HOME/.fehbg

source ~/.colours
# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload


# remove all existing keybindings
hc keyunbind --all
hc set default_frame_layout 3 # grid
# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt
#hc keybind $Mod-slash spawn dmenu_run -i -fn "-*-fixed-medium-*-*-*-*-*-*-*-*-*-*-*-*" -nb "#000" -nf "#FFF" -sb"#333"
hc keybind $Mod-slash spawn dmenu_run -i -p ?

#tags
TAG_NAMES=( 1 2 3 4 5 6 7 8 9 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]}; do
    key=$(( $i + 1 ))
    hc add "${TAG_NAMES[$i]}"
    if [ $key -lt 10 ]; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
hc keybind $Mod-0 use_index "9"
hc keybind $Mod-Shift-0 move_index "9"

# cycle through tags
hc keybind $Mod-period use_index +1
hc keybind $Mod-comma  use_index -1
hc keybind $Mod-Shift-Right cycle_monitor +1
hc keybind $Mod-Shift-Left cycle_monitor -1

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

hc keybind $Mod-Right spawn mpc next
hc keybind $Mod-Left spawn mpc prev
hc keybind $Mod-Up spawn mpc volume +1
hc keybind $Mod-Down spawn mpc volume -1
hc keybind $Mod-Shift-P spawn mpc play
hc keybind $Mod-Ctrl-l spawn xscreensaver-command -lock 

if [[ -x $HOME/scripts/herbstluftwm/splitter ]]; then
    hc keybind $Mod-F9 spawn $HOME/scripts/herbstluftwm/splitter nine
    hc keybind $Mod-F10 spawn $HOME/scripts/herbstluftwm/splitter three
    hc keybind $Mod-F11 spawn $HOME/scripts/herbstluftwm/splitter trip
    hc keybind $Mod-F12 spawn $HOME/scripts/herbstluftwm/splitter four
fi

if [[ -x $HOME/bin/herbstluftwm/closeall ]]; then
    hc keybind $Mod-BackSpace spawn $HOME/bin/herbstluftwm/closeall
fi

if [[ -x $HOME/randwallpaper.sh ]]; then
    hc keybind $Mod-Shift-BackSpace spawn $HOME/randwallpaper.sh
fi
# colors
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_transparent 1
hc set frame_bg_normal_color "$c_grey"
hc set frame_bg_active_color "$c_violet"
hc set frame_border_width 0
hc set window_border_width 2
hc set window_border_normal_color "$c_grey"
hc set window_border_active_color "$c_red"
hc set always_show_frame 1
hc set window_gap 1
hc set frame_gap 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
hc remove_monitor 1
hc move_monitor 0 1920x1080+0+0 0 0 21 1
hc add_monitor 1918x1080+1920+0 2

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

# find the panel
conky=~/.conkyrc
if [ -f "$conky" ]
    # start it on each monitor
    $conky  &
fi
